apiVersion: v1
kind: Service
metadata:
  name: connect-four-app-service
spec:
  selector:
    app: connect-four-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
